source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

use_frameworks!

platform :ios, '9.0'

target 'CitrusPay_Example' do
  pod 'CitrusPay', :path => '../../../../'  
end

target 'CitrusPay_Tests' do
  pod 'CitrusPay', :path => '../../../../'  
end